### PR TITLE
Kerberos authentication

### PR DESCRIPTION
**Pull request by catatonicprime**
Implements Enhancement [Issue 179](https://github.com/Azure/msrest-for-python/issues/179).

Additional changes include minor style guide (PEP8) changes.

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @catatonicprime could you confirm you tested it and it works on DevOps for instance? I don't have an easy way to test it right now.
Thanks!

**Comment by catatonicprime** [comment]
Yep - I tested against  an azure devops instance. I *did* not test for negative cases (e.g. when requests_kerberos is not installed). I did test that it succeeds when I initiate with a mutual_authentication of OPTIONAL and that it failed (for my use-case) when mutual authentication was not specified (which implies it is REQUIRED). I believe this is expected in *my* environment & the comments note why I believe this is acceptable (definitely open to feedback though). Unfortunately I don't think I can/want to share my surrounding "test" code as it's kind of not actually test code.

Hope this helps.

**Comment by lmazuel** [comment]
Thanks for the contribution @catatonicprime !!!

**Comment by catatonicprime** [comment]
Glad to help, I'll keep an eye out for when the release is available.

**Pull request merged**
