### PR TITLE
Delay load requests and oauthlib to improve module load performance f…

### LINKED ISSUE #23: Importing msrest.exceptions is expensive
Importing msrest pulls in quite a few modules (indirectly), including, but not limited to, requests, in its __init__.py. The azure-cli is working on startup performance, and are looking at delay loading modules as much as we can. 

Being able to at least use the exception classes from msrest without taking the module load hit would be a very welcome improvement.

### PR DESCRIPTION
**Pull request by johanste**
…or msrest.exceptions. Fixes #23

### CODE REVIEW

**Comment by brettcannon** [comment]
Do realize that by doing this you **MUST** make sure you never instantiate any of these classes in a thread as a side-effect of importing, else you will deadlock (common problem in the os module which uses a similar check).

And if you are doing this for performance then you can always use https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader which will work transparently for all imports.

**Comment by brettcannon** [comment]
To clarify what I mean by deadlocks from importing, see https://bugs.python.org/issue1590864 (I don't know how much this affects Python 3 as we tweaked the import lock, but this can affect Python 2).

**Comment by johanste** [comment]
@brettcannon, please correct me if I'm wrong, but using LazyLoader is only an option for Python 3.5+, correct?

**Comment by brettcannon** [comment]
@johanste Depends on what you mean by "option" 😉 It's in the stdlib starting in Python 3.5, but if importlib2 is tracking upstream recently enough you could use that to use the lazy loader.

**Comment by johanste** [comment]
@brettcannon, as always, you teach me something new. It looks like importlib2 has not been officially released, so I would personally be a bit hesitant to use that...

**Comment by brettcannon** [comment]
@johanste what do you mean by "official"? [importlib2](https://pypi.org/project/importlib2/) is as "official" as anything else on PyPI. 😉

Anyway, all I'm trying to say is what you're doing is basically fine, just if anyone ever reports some weird deadlocking problem then ask if they are using threads and if they are have them instantiate their classes ahead of time and/or don't launch a new thread as a side-effect of importing (and this might only be a Python 2 problem; haven't deal with this problem in years).

Or drop support up to Python 3.5. Whichever is easiest for you. 😁

**Comment by johanste** [comment]
I was referring to the following comments for the package:

> Note: This project is not yet released and the code base may be
> unstable. Currently the importlib tests all pass, but a few things
> remain to be done before the initial release.

I'll take a look at using LazyLoader in the az cli since we have quite a few instances where we want to postpone loading of stuff as long as we can... but I'm afraid I cannot drop <3.5 support right now. :)

**Comment by brettcannon** [comment]
@johanste if you are serious about using importlib2 I can talk to the maintainer as he's a friend of mine.

**Pull request closed without merging**
