### PR TITLE
Fix #11 - Allow polymorphic serialization from JSON like objects

### LINKED ISSUE #11: Support building instance from dict with polymorphic object
Currently the SDKs can accept a dict instead of a model and transform it to the right model automatically. This is not available if there is at any level a polymorphic object.

This should be possible looking at `_subtype_map` to identify the right instance type

FYI @annatisch @vishrutshah

### PR DESCRIPTION
**Pull request by lmazuel**
Didn't test with Autorest testsuite yet, but since this is JSON-like syntax, I'm pretty sure there is no test in Autorest anyway.

### CODE REVIEW

**Comment by lmazuel** [comment]
Tested by @vishrutshah on his Monitor issue and all SDK tests ok.

**Comment by lmazuel** [comment]
@annatisch I dig inside the msrest code and I realize I re-wrote `_classify` but calling it `_infer_type`. I will rework on this to simplify code and avoid duplication.

**Comment by annatisch** [comment]
@lmazuel - yes I thought there might be some duplication there - I was about to compare them myself :)

**Comment by lmazuel** [comment]
@annatisch if you have the time, I pushed an update that should still fix the serialization + the deserialisation at the time (rewriting classify to include both fix). I didn't launch Autorest tests or SDKs yet.

**Comment by lmazuel** [comment]
@annatisch I think everything is here and fix all these issues:
- https://github.com/Azure/autorest/issues/1729
- https://github.com/Azure/msrest-for-python/issues/11
- https://github.com/Azure/azure-sdk-for-python/issues/971
- https://github.com/Azure/azure-sdk-for-python/issues/970

Thoughts?

**Comment by annatisch** [comment]
@lmazuel - yup looks like it! :) Yay!

**Comment by lmazuel** [comment]
@annatisch last commit was debugged directly with @vishrutshah in peer programming. This allows to accept as key in the dict (serialisation) both the JSON key name and the Python key name.
Let's say RestAPI uses "awesomeName", so Python will use "awesome_name". Now for subtyping, both syntax are correct in a dict.
This allows to figure out subtyping even from a dict (serialisation) and from a JSON (deserialisation) even if the key are not expected to be the same. Also, it's been a long time I think about accepting both keys syntax in dict serialization (to simplify a copy/paste from a RestAPI example), so I'm shocked and don't consider this a hack.
Unittest to be added before merging this PR.

**Pull request merged**
